#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-crc32ex
Version  : 0.1.1
Release  : 1
URL      : https://github.com/tjake/crc32ex/archive/crc32ex-0.1.1.tar.gz
Source0  : https://github.com/tjake/crc32ex/archive/crc32ex-0.1.1.tar.gz
Source1  : http://repo1.maven.org/maven2/com/github/tjake/crc32ex/0.1.1/crc32ex-0.1.1.jar
Source2  : http://repo1.maven.org/maven2/com/github/tjake/crc32ex/0.1.1/crc32ex-0.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-crc32ex-data = %{version}-%{release}
Requires: mvn-crc32ex-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
CRC32Ex
=======
This library gives you a factory that, depending on your JVM version, will provide different implemetations on CRC32.

%package data
Summary: data components for the mvn-crc32ex package.
Group: Data

%description data
data components for the mvn-crc32ex package.


%package license
Summary: license components for the mvn-crc32ex package.
Group: Default

%description license
license components for the mvn-crc32ex package.


%prep
%setup -q -n crc32ex-crc32ex-0.1.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-crc32ex
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-crc32ex/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/tjake/crc32ex/0.1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/tjake/crc32ex/0.1.1/crc32ex-0.1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/tjake/crc32ex/0.1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/tjake/crc32ex/0.1.1/crc32ex-0.1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/tjake/crc32ex/0.1.1/crc32ex-0.1.1.jar
/usr/share/java/.m2/repository/com/github/tjake/crc32ex/0.1.1/crc32ex-0.1.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-crc32ex/LICENSE.txt
